# This is a basic workflow to help you get started with Actions

name: LuaCheck source folder

# Controls when the workflow will run (currently set to run manualy)
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  #
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v8.0.0
        
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0
        
      - name: Setup dependencies
        run: |
          luarocks install luacheck
          
      - name: luacheck source folder
        uses: nebularg/actions-luacheck@v1
        with:
          files: source/
          config: .luacheckrc
